"""Generate migration 039: add `p_vehicles text[]` to the returns RPCs.

Reliable transform (no hand-reproduction): fetch each function's exact
definition, (1) append the p_vehicles param to the arg list, (2) insert a
vehicle filter clause immediately after every p_excluded_trusts clause (every
function shares that pattern, and `ea` (entity_attribution) is in scope there).
Prints the migration body to stdout for review, then writes the file.
"""
from __future__ import annotations
import re, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from tracker.db import connect

FUNCS = [
    "nav_carryforward",
    "nav_carryforward_by_trust",
    "holdings_period_attribution",
    "monthly_security_attribution",
]
VEHICLE_PARAM = ", p_vehicles text[] DEFAULT NULL::text[]"
VEHICLE_CLAUSE = (
    "\n      AND (COALESCE(array_length(p_vehicles, 1), 0) = 0"
    "\n           OR ea.vehicle_alias = ANY(p_vehicles))"
)
# match the whole excluded_trusts AND-clause, however it's whitespaced
EXCL_RE = re.compile(
    r"\(COALESCE\(array_length\(p_excluded_trusts.*?ANY\(p_excluded_trusts\)\)\)",
    re.DOTALL,
)

conn = connect(); cur = conn.cursor()
out = [
    "-- 039_vehicle_on_returns_rpcs.sql",
    "-- Option C, Phase 2: add p_vehicles to the returns RPCs so the Vehicle/SPV",
    "-- filter scopes returns, the NAV-over-time chart and the Performance matrix.",
    "-- Generated by scripts/gen_migration_039.py from the live definitions; the",
    "-- only edits are the p_vehicles param + a vehicle_alias filter after each",
    "-- p_excluded_trusts clause. Apply manually in the Supabase SQL Editor.",
    "",
]
for fn in FUNCS:
    cur.execute(
        "SELECT pg_get_functiondef(p.oid) d FROM pg_proc p JOIN pg_namespace n "
        "ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname=%s "
        "ORDER BY array_length(p.proargnames,1) DESC LIMIT 1",  # widest overload
        (fn,),
    )
    d = cur.fetchone()["d"]
    # 1. add param to the arg list (the ')' just before RETURNS)
    d2, n1 = re.subn(r"\)\n RETURNS", VEHICLE_PARAM + ")\n RETURNS", d, count=1)
    # 2. insert the vehicle clause after each excluded_trusts clause
    d3, n2 = EXCL_RE.subn(lambda m: m.group(0) + VEHICLE_CLAUSE, d2)
    assert n1 == 1, f"{fn}: arg-list anchor not found"
    assert n2 >= 1, f"{fn}: no p_excluded_trusts clause found"
    print(f"-- {fn}: param+{n2} vehicle clause(s)", file=sys.stderr)
    out.append(d3.rstrip() + ";\n")
conn.close()

body = "\n".join(out)
Path("supabase/migrations/039_vehicle_on_returns_rpcs.sql").write_text(body, encoding="utf-8")
print(body)
