-- 039_vehicle_on_returns_rpcs.sql
-- Option C, Phase 2: add p_vehicles to the returns RPCs so the Vehicle/SPV
-- filter scopes returns, the NAV-over-time chart and the Performance matrix.
-- Generated by scripts/gen_migration_039.py from the live definitions; the
-- only edits are the p_vehicles param + a vehicle_alias filter after each
-- p_excluded_trusts clause. Apply manually in the Supabase SQL Editor.
--
-- Adding the p_vehicles param changes each function's signature, so the
-- CREATE OR REPLACE below creates a NEW overload and leaves the old one. Drop
-- the old (no-p_vehicles) overloads first — they're unused once the web always
-- passes p_vehicles, and they're cruft otherwise. Safe to re-run (IF EXISTS).
DROP FUNCTION IF EXISTS public.nav_carryforward(p_sub_client text, p_trusts text[], p_accounts text[], p_target_date date, p_asset_classes text[], p_excluded_trusts text[]);
DROP FUNCTION IF EXISTS public.nav_carryforward_by_trust(p_sub_client text, p_trusts text[], p_accounts text[], p_target_date date, p_asset_classes text[], p_excluded_trusts text[]);
DROP FUNCTION IF EXISTS public.holdings_period_attribution(p_sub_client text, p_trusts text[], p_accounts text[], p_asset_classes text[], p_excluded_trusts text[], p_end_date date, p_mtd_start date, p_ytd_start date, p_six_m_start date, p_one_y_start date);
DROP FUNCTION IF EXISTS public.monthly_security_attribution(p_sub_client text, p_trusts text[], p_accounts text[], p_asset_classes text[], p_from_month date, p_excluded_trusts text[]);
DROP FUNCTION IF EXISTS public.monthly_security_attribution(p_sub_client text, p_trusts text[], p_accounts text[], p_asset_classes text[], p_from_month date, p_excluded_trusts text[], p_top_per_month integer);

CREATE OR REPLACE FUNCTION public.nav_carryforward(p_sub_client text, p_trusts text[] DEFAULT NULL::text[], p_accounts text[] DEFAULT NULL::text[], p_target_date date DEFAULT NULL::date, p_asset_classes text[] DEFAULT NULL::text[], p_excluded_trusts text[] DEFAULT NULL::text[], p_vehicles text[] DEFAULT NULL::text[])
 RETURNS TABLE(nav numeric, anchor_date date)
 LANGUAGE sql
 STABLE
AS $function$
    WITH scope AS (
        SELECT DISTINCT sub_client_node_id
        FROM public.entity_attribution
        WHERE sub_client_alias = p_sub_client
          AND sub_client_node_id IS NOT NULL
    ),
    latest_per_account AS (
        SELECT ps.account_node_id, MAX(ps.snapshot_date) AS md
        FROM public.position_snapshot ps
        WHERE ps.snapshot_date <= p_target_date
          AND ps.sub_client_node_id IN (SELECT sub_client_node_id FROM scope)
        GROUP BY ps.account_node_id
    )
    SELECT COALESCE(SUM(ps.mv_reporting), 0)::numeric AS nav,
           MAX(ps.snapshot_date) AS anchor_date
    FROM public.position_snapshot ps
    JOIN latest_per_account lpa
      ON lpa.account_node_id = ps.account_node_id
     AND lpa.md = ps.snapshot_date
    LEFT JOIN public.entity_attribution ea ON ea.node_id   = ps.account_node_id
    LEFT JOIN public.security           s  ON s.security_id = ps.security_id
    WHERE ea.sub_client_alias = p_sub_client
      AND (COALESCE(array_length(p_trusts, 1), 0) = 0
           OR ea.trust_alias = ANY(p_trusts))
      AND (COALESCE(array_length(p_accounts, 1), 0) = 0
           OR ps.account_node_id = ANY(p_accounts))
      AND (COALESCE(array_length(p_asset_classes, 1), 0) = 0
           OR s.asset_class = ANY(p_asset_classes))
      AND (COALESCE(array_length(p_excluded_trusts, 1), 0) = 0
           OR NOT (ea.trust_alias = ANY(p_excluded_trusts)))
      AND (COALESCE(array_length(p_vehicles, 1), 0) = 0
           OR ea.vehicle_alias = ANY(p_vehicles));
$function$;

CREATE OR REPLACE FUNCTION public.nav_carryforward_by_trust(p_sub_client text, p_trusts text[] DEFAULT NULL::text[], p_accounts text[] DEFAULT NULL::text[], p_target_date date DEFAULT NULL::date, p_asset_classes text[] DEFAULT NULL::text[], p_excluded_trusts text[] DEFAULT NULL::text[], p_vehicles text[] DEFAULT NULL::text[])
 RETURNS TABLE(trust_alias text, nav numeric, anchor_date date)
 LANGUAGE sql
 STABLE
AS $function$
    -- Restrict the per-account MAX scan to this sub-client's accounts via the
    -- denormalised sub_client_node_id (+ its index, migration 028) instead of
    -- scanning every family's history.
    WITH scope AS (
        SELECT DISTINCT sub_client_node_id
        FROM public.entity_attribution
        WHERE sub_client_alias = p_sub_client
          AND sub_client_node_id IS NOT NULL
    ),
    latest_per_account AS (
        SELECT ps.account_node_id, MAX(ps.snapshot_date) AS md
        FROM public.position_snapshot ps
        WHERE ps.snapshot_date <= p_target_date
          AND ps.sub_client_node_id IN (SELECT sub_client_node_id FROM scope)
        GROUP BY ps.account_node_id
    )
    SELECT ea.trust_alias,
           COALESCE(SUM(ps.mv_reporting), 0)::numeric AS nav,
           MAX(ps.snapshot_date) AS anchor_date
    FROM public.position_snapshot ps
    JOIN latest_per_account lpa
      ON lpa.account_node_id = ps.account_node_id
     AND lpa.md = ps.snapshot_date
    JOIN public.entity_attribution ea ON ea.node_id    = ps.account_node_id
    JOIN public.security           s  ON s.security_id  = ps.security_id
    WHERE ea.sub_client_alias = p_sub_client
      AND ea.trust_alias IS NOT NULL
      AND (COALESCE(array_length(p_trusts, 1), 0) = 0
           OR ea.trust_alias = ANY(p_trusts))
      AND (COALESCE(array_length(p_accounts, 1), 0) = 0
           OR ps.account_node_id = ANY(p_accounts))
      AND (COALESCE(array_length(p_asset_classes, 1), 0) = 0
           OR s.asset_class = ANY(p_asset_classes))
      AND (COALESCE(array_length(p_excluded_trusts, 1), 0) = 0
           OR NOT (ea.trust_alias = ANY(p_excluded_trusts)))
      AND (COALESCE(array_length(p_vehicles, 1), 0) = 0
           OR ea.vehicle_alias = ANY(p_vehicles))
    GROUP BY ea.trust_alias;
$function$;

CREATE OR REPLACE FUNCTION public.holdings_period_attribution(p_sub_client text, p_trusts text[] DEFAULT NULL::text[], p_accounts text[] DEFAULT NULL::text[], p_asset_classes text[] DEFAULT NULL::text[], p_excluded_trusts text[] DEFAULT NULL::text[], p_end_date date DEFAULT NULL::date, p_mtd_start date DEFAULT NULL::date, p_ytd_start date DEFAULT NULL::date, p_six_m_start date DEFAULT NULL::date, p_one_y_start date DEFAULT NULL::date, p_vehicles text[] DEFAULT NULL::text[])
 RETURNS TABLE(period text, account_node_id text, security_id bigint, start_mv numeric, flows numeric, income numeric)
 LANGUAGE plpgsql
 STABLE
AS $function$
#variable_conflict use_column
DECLARE
    v_end_date date;
BEGIN
    v_end_date := COALESCE(p_end_date, CURRENT_DATE);

    RETURN QUERY
    WITH
    params AS (
        SELECT period, start_date
        FROM (VALUES
            ('mtd', p_mtd_start),
            ('ytd', p_ytd_start),
            ('6m',  p_six_m_start),
            ('1y',  p_one_y_start)
        ) AS t(period, start_date)
        WHERE start_date IS NOT NULL
    ),
    -- Currently-held (account × security) pairs in scope. Mirrors
    -- v_positions_refreshed: per-account MAX(snapshot_date) (no filter),
    -- then the asset_class filter is applied to the resulting rows. So
    -- the universe here matches the rows the Holdings table displays.
    latest_held AS (
        SELECT DISTINCT
            ps.account_node_id,
            ps.security_id
        FROM public.position_snapshot ps
        LEFT JOIN public.entity_attribution ea ON ea.node_id = ps.account_node_id
        LEFT JOIN public.security s            ON s.security_id = ps.security_id
        WHERE ea.sub_client_alias = p_sub_client
          AND (COALESCE(array_length(p_trusts,          1), 0) = 0
               OR ea.trust_alias    = ANY(p_trusts))
          AND (COALESCE(array_length(p_accounts,        1), 0) = 0
               OR ps.account_node_id = ANY(p_accounts))
          AND (COALESCE(array_length(p_excluded_trusts, 1), 0) = 0
               OR NOT (ea.trust_alias = ANY(p_excluded_trusts)))
      AND (COALESCE(array_length(p_vehicles, 1), 0) = 0
           OR ea.vehicle_alias = ANY(p_vehicles))
          AND (COALESCE(array_length(p_asset_classes,   1), 0) = 0
               OR s.asset_class = ANY(p_asset_classes)
               OR (s.asset_class IS NULL AND 'Unclassified' = ANY(p_asset_classes)))
          AND ps.snapshot_date = (
              SELECT MAX(ps2.snapshot_date)
              FROM public.position_snapshot ps2
              WHERE ps2.account_node_id = ps.account_node_id
          )
    ),
    -- For each (period × held pair), mv_reporting at the latest snapshot
    -- on or before the period's start_date. Correlated subquery: walks
    -- pos_snap_account_date_idx backwards from start_date. Bounded at
    -- ~(periods × holdings) iterations — small.
    start_mv_per AS (
        SELECT
            pa.period,
            lh.account_node_id,
            lh.security_id,
            COALESCE((
                SELECT ps.mv_reporting
                FROM public.position_snapshot ps
                WHERE ps.account_node_id = lh.account_node_id
                  AND ps.security_id     = lh.security_id
                  AND ps.snapshot_date  <= pa.start_date
                ORDER BY ps.snapshot_date DESC
                LIMIT 1
            ), 0)::numeric AS start_mv
        FROM params pa
        CROSS JOIN latest_held lh
    ),
    -- Per (period × held pair), Buy/Sell + income aggregates over the
    -- period window. JOIN to latest_held filters out transactions on
    -- pairs no longer held — consistent with the Holdings page only
    -- showing current positions.
    txns_per AS (
        SELECT
            pa.period,
            t.account_node_id,
            t.security_id,
            SUM(CASE WHEN t.transaction_type_clean IN ('Buy', 'Sell')
                     THEN -t.net_amount_reporting ELSE 0 END)::numeric AS flows,
            SUM(CASE WHEN t.transaction_type_clean IN ('Cash Dividends', 'Interest', 'Income')
                     THEN t.net_amount_reporting ELSE 0 END)::numeric AS income
        FROM params pa
        JOIN public.transaction_log t
          ON t.transaction_date >  pa.start_date
         AND t.transaction_date <= v_end_date
        JOIN latest_held lh
          ON lh.account_node_id = t.account_node_id
         AND lh.security_id     = t.security_id
        WHERE t.transaction_type_clean IN ('Buy', 'Sell',
                                           'Cash Dividends', 'Interest', 'Income')
          AND t.security_id IS NOT NULL
        GROUP BY pa.period, t.account_node_id, t.security_id
    )
    SELECT
        smv.period::text,
        smv.account_node_id::text,
        smv.security_id::bigint,
        smv.start_mv,
        COALESCE(tp.flows,  0)::numeric AS flows,
        COALESCE(tp.income, 0)::numeric AS income
    FROM start_mv_per smv
    LEFT JOIN txns_per tp
           ON tp.period          = smv.period
          AND tp.account_node_id = smv.account_node_id
          AND tp.security_id     = smv.security_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.monthly_security_attribution(p_sub_client text, p_trusts text[] DEFAULT NULL::text[], p_accounts text[] DEFAULT NULL::text[], p_asset_classes text[] DEFAULT NULL::text[], p_from_month date DEFAULT NULL::date, p_excluded_trusts text[] DEFAULT NULL::text[], p_top_per_month integer DEFAULT NULL::integer, p_vehicles text[] DEFAULT NULL::text[])
 RETURNS TABLE(month date, security_id bigint, asset_name text, ticker_masttro text, asset_class text, start_mv numeric, end_mv numeric, flows numeric, income numeric, gain numeric)
 LANGUAGE plpgsql
 STABLE
AS $function$
#variable_conflict use_column
DECLARE
    v_internal_from date;
BEGIN
    v_internal_from := COALESCE(
        (date_trunc('month', p_from_month) - interval '1 month')::date,
        '1900-01-01'::date
    );

    RETURN QUERY
    WITH
    scoped_positions AS (
        SELECT
            ps.snapshot_date,
            ps.security_id,
            SUM(ps.mv_reporting) AS mv_total
        FROM public.position_snapshot ps
        LEFT JOIN public.entity_attribution ea ON ea.node_id = ps.account_node_id
        LEFT JOIN public.security s            ON s.security_id = ps.security_id
        WHERE ea.sub_client_alias = p_sub_client
          AND (COALESCE(array_length(p_trusts,          1), 0) = 0
               OR ea.trust_alias    = ANY(p_trusts))
          AND (COALESCE(array_length(p_accounts,        1), 0) = 0
               OR ps.account_node_id = ANY(p_accounts))
          AND (COALESCE(array_length(p_excluded_trusts, 1), 0) = 0
               OR NOT (ea.trust_alias = ANY(p_excluded_trusts)))
      AND (COALESCE(array_length(p_vehicles, 1), 0) = 0
           OR ea.vehicle_alias = ANY(p_vehicles))
          AND (COALESCE(array_length(p_asset_classes,   1), 0) = 0
               OR s.asset_class = ANY(p_asset_classes)
               OR (s.asset_class IS NULL AND 'Unclassified' = ANY(p_asset_classes)))
          AND ps.snapshot_date >= v_internal_from
        GROUP BY ps.snapshot_date, ps.security_id
    ),
    monthly_end AS (
        SELECT DISTINCT ON (date_trunc('month', sp.snapshot_date), sp.security_id)
            date_trunc('month', sp.snapshot_date)::date AS month,
            sp.security_id,
            sp.mv_total AS end_mv
        FROM scoped_positions sp
        ORDER BY date_trunc('month', sp.snapshot_date),
                 sp.security_id,
                 sp.snapshot_date DESC
    ),
    monthly_txns AS (
        SELECT
            date_trunc('month', t.transaction_date)::date AS month,
            t.security_id,
            SUM(CASE WHEN t.transaction_type_clean IN ('Buy', 'Sell')
                     THEN -t.net_amount_reporting ELSE 0 END)::numeric AS flows,
            SUM(CASE WHEN t.transaction_type_clean IN ('Cash Dividends', 'Interest', 'Income')
                     THEN t.net_amount_reporting ELSE 0 END)::numeric AS income
        FROM public.transaction_log t
        LEFT JOIN public.entity_attribution ea ON ea.node_id = t.account_node_id
        LEFT JOIN public.security s            ON s.security_id = t.security_id
        WHERE ea.sub_client_alias = p_sub_client
          AND (COALESCE(array_length(p_trusts,          1), 0) = 0
               OR ea.trust_alias    = ANY(p_trusts))
          AND (COALESCE(array_length(p_accounts,        1), 0) = 0
               OR t.account_node_id = ANY(p_accounts))
          AND (COALESCE(array_length(p_excluded_trusts, 1), 0) = 0
               OR NOT (ea.trust_alias = ANY(p_excluded_trusts)))
      AND (COALESCE(array_length(p_vehicles, 1), 0) = 0
           OR ea.vehicle_alias = ANY(p_vehicles))
          AND (COALESCE(array_length(p_asset_classes,   1), 0) = 0
               OR s.asset_class = ANY(p_asset_classes)
               OR (s.asset_class IS NULL AND 'Unclassified' = ANY(p_asset_classes)))
          AND t.transaction_type_clean IN ('Buy', 'Sell',
                                           'Cash Dividends', 'Interest', 'Income')
          AND t.transaction_date >= v_internal_from
          AND t.security_id IS NOT NULL
        GROUP BY date_trunc('month', t.transaction_date), t.security_id
    ),
    universe AS (
        SELECT month, security_id FROM monthly_end
        UNION
        SELECT month, security_id FROM monthly_txns
    ),
    enriched AS (
        SELECT
            u.month,
            u.security_id,
            COALESCE(me.end_mv,      0)::numeric AS end_mv,
            COALESCE(prev_me.end_mv, 0)::numeric AS start_mv,
            COALESCE(mt.flows,       0)::numeric AS flows,
            COALESCE(mt.income,      0)::numeric AS income,
            ((COALESCE(me.end_mv, 0) - COALESCE(prev_me.end_mv, 0))
                - COALESCE(mt.flows, 0)
                + COALESCE(mt.income, 0))::numeric AS gain
        FROM universe u
        LEFT JOIN monthly_end me
               ON me.month = u.month AND me.security_id = u.security_id
        LEFT JOIN monthly_end prev_me
               ON prev_me.security_id = u.security_id
              AND prev_me.month = (u.month - interval '1 month')::date
        LEFT JOIN monthly_txns mt
               ON mt.month = u.month AND mt.security_id = u.security_id
    ),
    ranked AS (
        SELECT
            e.*,
            ROW_NUMBER() OVER (PARTITION BY e.month ORDER BY e.gain DESC) AS rank_pos,
            ROW_NUMBER() OVER (PARTITION BY e.month ORDER BY e.gain ASC)  AS rank_neg
        FROM enriched e
        WHERE e.month >= COALESCE(p_from_month, '1900-01-01'::date)
    )
    SELECT
        r.month,
        r.security_id::bigint,
        s.asset_name::text,
        s.ticker_masttro::text,
        COALESCE(s.asset_class, 'Unclassified')::text AS asset_class,
        r.start_mv,
        r.end_mv,
        r.flows,
        r.income,
        r.gain
    FROM ranked r
    LEFT JOIN public.security s ON s.security_id = r.security_id
    WHERE p_top_per_month IS NULL
       OR r.rank_pos <= p_top_per_month
       OR r.rank_neg <= p_top_per_month
    ORDER BY r.month, r.gain DESC;
END;
$function$;
